apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        envFrom:
          - configMapRef:
              name: {{ .Values.appName }}-config
          - configMapRef:
              name: {{ .Values.appName }}-wp-config
          - secretRef:
              name: {{ .Values.appName }}-secret
        env:
        - name: PODNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        {{- range .Values.volumeMounts }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
        {{- end }}
      volumes:
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolume.name }}

---
{{- if .Values.phpmyadmin.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-pma
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: {{ .Values.appName }}-pma
  template:
    metadata:
      labels:
        app.kubernetes.io/app: {{ .Values.appName }}-pma
    spec:
      containers:
      - name: {{ .Values.appName }}-pma
        image: "phpmyadmin/phpmyadmin"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.phpmyadmin.port }}
        envFrom:
          - configMapRef:
              name: {{ .Values.appName }}-config
          - secretRef:
              name: {{ .Values.appName }}-secret
{{- end }}