apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.appName }}-wp-config"
data:
  WORDPRESS_CONFIG_EXTRA: |
    define('WP_HOME', '{{ .Values.configMap.WP_HOME }}');
    define('WP_SITEURL', '{{ .Values.configMap.WP_HOME }}');